permalink: /posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Valerie Ang
url: http://valerieang.com
description: learning git, ruby, jekyll, terminal, in the process of putting this site up 
twitter: valriri
